// Generated by Supabase CLI
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          created_at: string | null
        }
        Insert: {
          id: string
          username: string
          created_at?: string | null
        }
        Update: {
          id?: string
          username?: string
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      forum_posts: {
        Row: {
          id: string
          title: string
          content: string
          user_id: string
          course_id: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          title: string
          content: string
          user_id: string
          course_id?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          title?: string
          content?: string
          user_id?: string
          course_id?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "forum_posts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "forum_posts_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "new_courses"
            referencedColumns: ["id"]
          }
        ]
      }
      forum_replies: {
        Row: {
          id: string
          post_id: string
          content: string
          user_id: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          post_id: string
          content: string
          user_id: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          post_id?: string
          content?: string
          user_id?: string
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "forum_replies_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "forum_posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "forum_replies_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      majors: {
        Row: {
          id: string
          name: string
          slug: string
          created_at: string | null
        }
        Insert: {
          id?: string
          name: string
          slug: string
          created_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          created_at?: string | null
        }
        Relationships: []
      }
      subfields: {
        Row: {
          id: string
          major_id: string
          name: string
          slug: string
          created_at: string | null
        }
        Insert: {
          id?: string
          major_id: string
          name: string
          slug: string
          created_at?: string | null
        }
        Update: {
          id?: string
          major_id?: string
          name?: string
          slug?: string
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "subfields_major_id_fkey"
            columns: ["major_id"]
            isOneToOne: false
            referencedRelation: "majors"
            referencedColumns: ["id"]
          }
        ]
      }
      admin_users: {
        Row: {
          created_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_users_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      new_courses: {
        Row: {
          id: string
          subfield_id: string
          code: string
          title: string
          ects: number
          description: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          subfield_id: string
          code: string
          title: string
          ects: number
          description?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          subfield_id?: string
          code?: string
          title?: string
          ects?: number
          description?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "courses_subfield_id_fkey"
            columns: ["subfield_id"]
            isOneToOne: false
            referencedRelation: "subfields"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_catalogue: {
        Args: Record<string, never>
        Returns: Json
      }
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}